#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - gpg
  - lsb-release
  - software-properties-common
  - containerd
  - kubeadm
  - kubelet
  - kubectl
  - ufw
  - locales

write_files:
  - path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  - path: /etc/sysctl.d/99-kubernetes-k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1

runcmd:
  - apt install gnupg2 -y
  - locale-gen en_US.UTF-8
  - update-locale LANG=en_US.UTF-8
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  - modprobe overlay 
  - modprobe br_netfilter
  - sysctl --system
  - apt install containerd -y
  - mkdir -p /etc/containerd
  - containerd config default > /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl
  - systemctl enable kubelet
  - systemctl start kubelet
  - apt-get install -y ufw
  - ufw allow ssh
  - ufw allow 179/tcp   # Calico
  - ufw allow 2379:2380/tcp # etcd server client API
  - ufw allow 6443/tcp  # Kubernetes API server
  - ufw allow 10250/tcp # Kubelet API
  - ufw allow 10251/tcp # kube-scheduler
  - ufw allow 10252/tcp # kube-controller-manager
  - ufw allow 10255/tcp # Read-only Kubelet API
  - ufw allow 2049/tcp  # Portworx
  - ufw allow 3000/tcp  # Portworx
  - ufw allow 3260/tcp  # Portworx
  - ufw allow 9001/tcp  # Portworx
  - ufw --force enable
  - systemctl start ufw
  - kubeadm config images pull
  - systemctl restart kubelet
  - ufw status verbose > /var/log/ufw_status.log
  - echo "UFW installation and configuration completed."
